# Generated by Django 4.2 on 2023-04-19 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='eleicao_ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='eleicao_data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 9, 59, 35, 688335)),
        ),
    ]
