# Generated by Django 4.2 on 2023-04-19 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_alter_eleicao_eleicao_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dado_eleicao',
            name='eleicao_nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='eleicao_data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 19, 10, 2, 5, 748943)),
        ),
    ]
