# Generated by Django 4.2 on 2023-04-24 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0004_remove_dado_eleicao_eleicao_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleicao',
            name='eleicao_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eleicao',
            name='eleicao_data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 24, 13, 38, 46, 956213)),
        ),
    ]
